---
kind: pipeline
type: kubernetes
name: build

environment:
  NAME: sqs_exporter

trigger:
  event:
    - push

steps:
  - name: publish_to_ecr
    image: plugins/ecr
    environment:
      AWS_ACCOUNT_ID:
        from_secret: AWS_ACCOUNT_ID
      AWS_ACCESS_KEY_ID:
        from_secret: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        from_secret: AWS_SECRET_ACCESS_KEY
    settings:
      access_key:
        from_secret: AWS_ACCESS_KEY_ID
      secret_key:
        from_secret: AWS_SECRET_ACCESS_KEY
      repo: sqs-exporter
      tags: 1.0.0
      registry: ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com
      cache_from: ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/sqs-exporter:1.0.0
      region: us-east-1
      build_args:
        - BUILD_NUM=drone-${DRONE_BUILD_NUMBER}
        - SHA1=${DRONE_COMMIT_SHA}
    when:
      branch:
        - master

---
kind: pipeline
type: kubernetes
name: pr

trigger:
  event:
    - pull_request

steps:
  - name: pr-dummy-step
    pull: always
    image: plugins/ecr
    environment:
      ACCOUNT_ID:
        from_secret: AWS_ACCOUNT_ID
    commands:
      - echo "Dummy step $ACCOUNT_ID"

---
kind: secret
name: AWS_ACCOUNT_ID
get:
  path: secrets/dev/drone
  name: AWS_ACCOUNT_ID

---
kind: secret
name: DRONE_API_TOKEN
get:
  path: secrets/dev/drone
  name: DRONE_API_TOKEN

---
kind: secret
name: AWS_ACCESS_KEY_ID
get:
  path: secrets/dev/drone
  name: DRONE_AWS_ACCESS_KEY

---
kind: secret
name: AWS_SECRET_ACCESS_KEY
get:
  path: secrets/dev/drone
  name: DRONE_AWS_ACCESS_SECRET_KEY

